name: sys-pana-example-api

on:
  push:
    branches: [main, develop]
    paths:
      - 'sys-pana-api/**'
      - '.github/workflows/sys-pana-example-api.yml'
  pull_request:
    paths:
      - 'sys-pana-api/**'
      - '.github/workflows/sys-pana-example-api.yml'
env:
  ANYPOINT_APP_NAME: dev-sys-pana-example-api
  ANYPOINT_ENVIRONMENT: 'Sandbox'
  POSTMAN_COLLECTION: postman-api-scenario-test/sys/sys-pana-example-api.postman_collection.json
  PROJECT_NAME: sys-pana-api
jobs:
  munit-deploy-apiTest-undeploy-slackNotification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 準備.
      - name: Setup JDK 1.8
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        if: ${{ false }} 
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Node
        if: ${{ false }} 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # MUnit Test.
      - name: MUnit Test
        if: ${{ false }} 
        id: MUnit
        run: mvn test -P test -Dapp-name=kdev-$ANYPOINT_APP_NAME -Danypoint.username=${{ secrets.FLECT_ANYPOINT_USER }} -Danypoint.password=${{ secrets.FLECT_ANYPOINT_PASSWORD }} -Dworker-cnt=1 -Dworker-type=MICRO -DmuleDeploy -s settings.xml -f $PROJECT_NAME/pom.xml --batch-mode --update-snapshots verify
      # Anypoint CLI の準備
      - name: Setup Anypoint CLI
        if: ${{ false }}
        run: sudo npm install -g anypoint-cli-v4 ; anypoint-cli-v4 plugins:install anypoint-cli-cloudhub-plugin ; anypoint-cli-v4 plugins:install anypoint-cli-designcenter-plugin; anypoint-cli-v4 conf username ${{ secrets.FLECT_ANYPOINT_USER }} ; anypoint-cli-v4 conf password ${{ secrets.FLECT_ANYPOINT_PASSWORD }} ; anypoint-cli-v4 conf organization ${{ secrets.FLECT_ANYPOINT_ORGANIZATION }} ; anypoint-cli-v4 conf environment $ANYPOINT_ENVIRONMENT
      # CloudHub へのデプロイ
      - name: Deploy On Anypoint Platform 
        if: ${{ false }}
        id: deploy
        run: mvn -e deploy -P dev -Dapp-name=$ANYPOINT_APP_NAME -Danypoint.username=${{ secrets.FLECT_ANYPOINT_USER }} -Danypoint.password=${{ secrets.FLECT_ANYPOINT_PASSWORD }} -Dworker-cnt=1 -Dworker-type=MICRO -DskipTests -DmuleDeploy -s settings.xml -f $PROJECT_DIRECTORY/pom.xml --batch-mode --update-snapshots verify
      # Newman のインストール
      - name: Newman Install
        if: ${{ false }} 
        run: sudo npm install -g newman
      # Postman によるAPI シナリオテスト.
      - name: API Scenario Test
        if: ${{ false }} 
        id: scenarioTest
        run: newman run $POSTMAN_COLLECTION --verbose
      # アプリケーションの削除
      - name: Delete Application
        if: ${{ false || steps.scenarioTest.conclusion == 'failure' }}
        run: anypoint-cli-v4 runtime-mgr:cloudhub-application:delete $ANYPOINT_APP_NAME
      # 上記までの処理が成功した場合、以下の成功通知処理が実行される
      - name: Slack Notification Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: good
          SLACK_TITLE: Success to Deploy to GitHub Pages :rocket:'
          SLACK_MESSAGE: ':closed_book: ${{ github.repository }}' 
      # 上記までの処理が成功した場合、以下の成功通知処理が実行される
      - name: Teams Notification Success
        if: ${{ success() }}
        run: curl -H '${{ format('Content-Type{0} application/json', ':') }}' -d '${{ format('{{"@type"{0}"MessageCard","@context"{0}"http://schema.org/extensions","themeColor"{0}"0076D7","summary"{0}"GitHubActionsNotification","sections"{0}[{{"activityTitle"{0}"GitHubActionsNotification","activitySubtitle"{0}"ResultofGitHubActionisSuccess.","activityImage"{0}"https://illustimage.com/photo/14305.png","facts"{0}[{{"name"{0}"担当者","value"{0}"{1}"}},{{"name"{0}"イベント","value"{0}"{2}"}},{{"name"{0}"GitHubActionsURL","value"{0}"{3}/{4}/actions/runs/{5}"}}],"markdown"{0}true}}]}}, {{"name"{0}"プルリクエスト URL","value"{0}"{6}"}}', ':', github.actor, github.event_name, github.server_url, github.repository, github.run_id, github.event.pull_request.html_url ) }}' ${{ secrets.TEAMS_WEBHOOK }}
      # 上記までの処理のいずれかが失敗した場合、以下の失敗通知処理が実行される
      - name: Slack Notification Failure
        if: ${{ failure() }} # ← 上記までのいずれかが失敗した場合にこの条件が真になる.
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: danger
          SLACK_TITLE: 'Failure to Deploy to GitHub Pages :boom:'
          SLACK_MESSAGE: ':closed_book: ${{ github.repository }}'
      # 上記までの処理のいずれかが失敗した場合、以下の失敗通知処理が実行される
      - name: Teams Notification Failure
        if: ${{ failure()  }}
        run: curl -H '${{ format('Content-Type{0} application/json', ':') }}' -d '${{ format('{{"@type"{0}"MessageCard","@context"{0}"http://schema.org/extensions","themeColor"{0}"0076D7","summary"{0}"GitHubActionsNotification","sections"{0}[{{"activityTitle"{0}"GitHubActionsNotification","activitySubtitle"{0}"ResultofGitHubActionisFailure.","activityImage"{0}"https://illust8.com/wp-content/uploads/2018/08/mark_batsu_illust_898.png","facts"{0}[{{"name"{0}"担当者","value"{0}"{1}"}},{{"name"{0}"イベント","value"{0}"{2}"}},{{"name"{0}"GitHubActionsURL","value"{0}"{3}/{4}/actions/runs/{5}"}}],"markdown"{0}true}}]}}, {{"name"{0}"プルリクエスト URL","value"{0}"{6}"}}', ':', github.actor, github.event_name, github.server_url, github.repository, github.run_id, github.event.pull_request.html_url ) }}' ${{ secrets.TEAMS_WEBHOOK }}
  uploadIfSpecification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 準備
      - name: Setup Node
        if: ${{ github.event_name == 'push' }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # Anypoint CLI の準備
      - name: Setup Anypoint CLI
        if: ${{ github.event_name == 'push' }}
        id: anypoint-cli-prepare
        run: sudo npm install -g anypoint-cli-v4 ; anypoint-cli-v4 plugins:install anypoint-cli-cloudhub-plugin ; anypoint-cli-v4 plugins:install anypoint-cli-designcenter-plugin; anypoint-cli-v4 conf username ${{ secrets.FLECT_ANYPOINT_USER }} ; anypoint-cli-v4 conf password ${{ secrets.FLECT_ANYPOINT_PASSWORD }} ; anypoint-cli-v4 conf organization ${{ secrets.FLECT_ANYPOINT_ORGANIZATION }} ; anypoint-cli-v4 conf environment $ANYPOINT_ENVIRONMENT
      # IF 仕様書の Design Center でのアップデート
      - name: Upload IF Specification
        if: ${{ steps.anypoint-cli-prepare.conclusion == 'success' }}
        id: upload-if-specification
        run: anypoint-cli-v4 designcenter:project:upload $PROJECT_NAME $PROJECT_NAME/src/main/resources/api || anypoint-cli-v4 designcenter:project:create $PROJECT_NAME $PROJECT_NAME/src/main/resources/api
      # 上記までの処理が成功した場合、以下の成功通知処理が実行される
      - name: Slack Notification Success
        if: ${{ github.event_name == 'push' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: good
          SLACK_TITLE: Success to Deploy to GitHub Pages :rocket:'
          SLACK_MESSAGE: ':closed_book: ${{ github.repository }}' 
      # 上記までの処理のいずれかが失敗した場合、以下の失敗通知処理が実行される
      - name: Slack Notification Failure
        if: ${{ failure() }} # ← 上記までのいずれかが失敗した場合にこの条件が真になる.
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: danger
          SLACK_TITLE: 'Failure to Deploy to GitHub Pages :boom:'
          SLACK_MESSAGE: ':closed_book: ${{ github.repository }}'